###
GET http://localhost:5000

###
GET http://localhost:5000/items

###
GET http://green-ocean-8a1780445b5f4a188ad5d9919c43f835.azurewebsites.net


###
GET http://bugaboxes.azurewebsites.net/json

###
GET http://bugaboxes.azurewebsites.net/

###
GET http://bugaboxes.azurewebsites.net/json

###
POST http://bugaboxes.azurewebsites.net/ask/
Content-Type: application/json

{
    "question":"what is my name"
}

###
POST http://localhost:5000/ask/
Content-Type: application/json

{
    "question":"what is my name"
}

###
GET http://localhost:5000/jsony
